### ISSUE TITLE
Add Stanford and SUL headers and footers

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/MyAccount#2]

**Comment by jvine** [comment]
Basic page layout should look like this:

![myaccount-basic-layout](https://cloud.githubusercontent.com/assets/6945691/25682189/1881d44e-300c-11e7-95e6-6102327f2daa.png)

The library website has the current official header and footer logos (as svg), as well as the footer links:
http://library.stanford.edu/sites/all/themes/sulair2016/logo.svg
http://library.stanford.edu/sites/all/themes/sulair2016/assets/images/sul-logo-stacked.svg

@jgreben the current HTML (that you sent me 5/2) is not quite right - the footer is not correctly pinned to the bottom of the viewport. I think the problem is here:

```
             </div>
           </div>
         </div>
       </div>

       <footer role="“contentinfo”">
```
which I think should be:
```
             </section>
           </div>
         </div>
       </div>

       <footer role="“contentinfo”">
```
because the <section> above is not closed, but there's an extra </div> at the end.
